export const SEARCH_MOVIE ='SEARCH_MOVIE'
export const SEARCH_BYRATE ='SEARCH_BYRATE'
export const ADD_MOVIE ='ADD_MOVIE'
export const EDIT_MOVIE ='EDIT_MOVIE'
export const UPDATE_MOVIE ='UPDATE_MOVIE'
export const REMOVE_MOVIE ='REMOVE_MOVIE'

